// Builds site/data/geo.js from Natural Earth (via the world-atlas package):
//  - a land mask rasterised onto the game grid
//  - simplified coastline rings and modern borders for drawing
import { readFileSync, writeFileSync } from 'node:fs';
import { feature, mesh } from 'topojson-client';
import { LON0, LON1, LAT0, LAT1, COLS, ROWS, toGrid, encodeRLE } from '../site/js/grid.js';

const load = (f) => JSON.parse(readFileSync(new URL(`../node_modules/world-atlas/${f}`, import.meta.url)));
const PAD = 0.5;
const inBox = ([lon, lat]) => lon > LON0 - PAD && lon < LON1 + PAD && lat > LAT0 - PAD && lat < LAT1 + PAD;

function rings(geom) {
  const polys = geom.type === 'Polygon' ? [geom.coordinates] : geom.type === 'MultiPolygon' ? geom.coordinates : [];
  return polys.flat();
}

// ---- Land mask (scanline fill of 10m land at cell centres) ----
const land10 = load('land-10m.json');
const landRings = feature(land10, land10.objects.land).features.flatMap((f) => rings(f.geometry))
  .filter((r) => r.some(inBox))
  .map((r) => r.map(([lon, lat]) => toGrid(lon, lat)));

// Scanline even-odd fill of rings (in grid coordinates) at cell centres.
function fill(ringList, mask, value) {
  for (let row = 0; row < ROWS; row++) {
    const y = row + 0.5;
    const xs = [];
    for (const r of ringList) {
      for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
        const [x1, y1] = r[i], [x2, y2] = r[j];
        if ((y1 > y) !== (y2 > y)) xs.push(x1 + ((y - y1) * (x2 - x1)) / (y2 - y1));
      }
    }
    xs.sort((a, b) => a - b);
    for (let k = 0; k + 1 < xs.length; k += 2) {
      const a = Math.max(0, Math.ceil(xs[k] - 0.5)), b = Math.min(COLS - 1, Math.floor(xs[k + 1] - 0.5));
      for (let c = a; c <= b; c++) mask[row * COLS + c] = value;
    }
  }
}
const mask = new Uint8Array(COLS * ROWS);
fill(landRings, mask, 1);

// Italy and Malta are outside the game. Keep the Trieste/Gorizia corner,
// which was Austrian in 1878.
const c10 = load('countries-10m.json');
const excluded = feature(c10, c10.objects.countries).features
  .filter((f) => ['380', '470', '674', '336'].includes(String(f.id)))
  .flatMap((f) => rings(f.geometry))
  .map((r) => r.filter(([lon, lat]) => !(lon > 13.3 && lat > 45.55)).map(([lon, lat]) => toGrid(lon, lat)))
  .filter((r) => r.length > 2);
fill(excluded, mask, 0);

// ---- Vector outlines, clipped loosely to the box and simplified ----
function simplify(pts, tol) {
  if (pts.length < 3) return pts;
  const out = [pts[0]];
  for (let i = 1; i < pts.length - 1; i++) {
    const [px, py] = out[out.length - 1];
    if (Math.hypot(pts[i][0] - px, pts[i][1] - py) >= tol) out.push(pts[i]);
  }
  out.push(pts[pts.length - 1]);
  return out;
}
const round = (p) => [Math.round(p[0] * 10) / 10, Math.round(p[1] * 10) / 10];
function clipLines(lines, tol) {
  const out = [];
  for (const line of lines) {
    let cur = [];
    for (const p of line) {
      if (inBox(p)) cur.push(round(toGrid(...p)));
      else if (cur.length) { cur.push(round(toGrid(...p))); out.push(cur); cur = []; }
    }
    if (cur.length > 1) out.push(cur);
  }
  return out.map((l) => simplify(l, tol)).filter((l) => l.length > 1);
}

const land50 = load('land-50m.json');
const coast = clipLines(feature(land50, land50.objects.land).features.flatMap((f) => rings(f.geometry)), 0.6);
const c50 = load('countries-50m.json');
const borders = clipLines(mesh(c50, c50.objects.countries, (a, b) => a !== b).coordinates, 0.8);

// Drop outlines of excluded land (Italy): lines whose points mostly sit on
// excluded cells or open sea west of the Adriatic.
const italyMask = new Uint8Array(COLS * ROWS);
fill(excluded, italyMask, 1);
const onItaly = (l) => l.filter(([x, y]) => {
  for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
    const cx = Math.floor(x) + dx, cy = Math.floor(y) + dy;
    if (cx >= 0 && cy >= 0 && cx < COLS && cy < ROWS && italyMask[cy * COLS + cx]) return true;
  }
  return false;
}).length > l.length * 0.5;
const drawnLand = { coast: coast.filter((l) => !onItaly(l)), borders: borders.filter((l) => !onItaly(l)) };

const js = `// Generated by tools/build-geo.mjs from Natural Earth (public domain) via world-atlas. Do not edit.
export const LAND_RLE = ${JSON.stringify(encodeRLE(mask))};
export const COAST = ${JSON.stringify(drawnLand.coast)};
export const MODERN_BORDERS = ${JSON.stringify(drawnLand.borders)};
`;
writeFileSync(new URL('../site/data/geo.js', import.meta.url), js);
console.log(`grid ${COLS}x${ROWS}, land cells ${mask.reduce((a, b) => a + b, 0)}, coast lines ${coast.length}, ${(js.length / 1024).toFixed(0)} KB`);
